[env:heltec_wireless_paper_v1_2]
platform  = espressif32
board     = heltec_wireless_paper
framework = arduino

lib_deps =
    jgromes/RadioLib @ ^7.1.0

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_speed  = 115200
upload_speed   = 921600
